#pragma once

#define RGB_MATRIX_DEFAULT_SPD 60
#define MIDI_BASIC
#define DEBOUNCE 10
#define USB_SUSPEND_WAKEUP_DELAY 0

#define PLANCK_EZ_LED_LOWER 12
#define PLANCK_EZ_LED_RAISE 13
#define PLANCK_EZ_LED_ADJUST 14

#define ORYX_CONFIGURATOR
#define FIRMWARE_VERSION u8"BOlDQ/bPA37"
